# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 68e85edf06c0bd842ef768ae333af7f9bb282bf6377e11ced571ec043bee732e2bbbeaa956f378385f30ab43feabee134ce9ddb900d799c18c391251ccf8cc7f

test:
  secret_key_base: 3ac3d918ae34f39ee456ce11664006aa36dea25f7a98e2ca17df910abd5aa21a239038c8011188b2346802f7c6721b5759abae30a8d960694cf4b816b6b9581f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
